name: Deploy to ECS (same-tag rollout)

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ap-northeast-1
  ACCOUNT_ID: "291234479055"
  ECR_REPO: voicebot
  IMAGE_TAG: v1
  CLUSTER_ARN: arn:aws:ecs:ap-northeast-1:291234479055:cluster/voicebot-cluster
  SERVICE_ARN: arn:aws:ecs:ap-northeast-1:291234479055:service/voicebot-cluster/svc-voicebot

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - uses: aws-actions/amazon-ecr-login@v2
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}
      - name: Force new deployment
        run: |
          aws ecs update-service \
            --cluster "${{ env.CLUSTER_ARN }}" \
            --service "${{ env.SERVICE_ARN }}" \
            --force-new-deployment \
            --region "${{ env.AWS_REGION }}"
