name: Deploy to ECS (same-tag rollout)

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: ap-northeast-1
  ACCOUNT_ID: "291234479055"
  ECR_REPO: voicebot
  IMAGE_TAG: ${{ github.sha }}  # ← ここがポイント：常にコミットSHAでタグ付け
  CLUSTER_ARN: arn:aws:ecs:ap-northeast-1:291234479055:cluster/voicebot-cluster
  SERVICE_ARN: arn:aws:ecs:ap-northeast-1:291234479055:service/voicebot-cluster/svc-voicebot

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Who am I (STS)
        run: aws sts get-caller-identity

      - name: Ensure ECR repository exists
        shell: bash
        run: |
          set -euo pipefail
          aws ecr describe-repositories --repository-names "${ECR_REPO}" >/dev/null 2>&1 || \
          aws ecr create-repository --repository-name "${ECR_REPO}" >/dev/null

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # ====== ここでデプロイスタンプを毎回書き直す（app.py の /version で表示される）======
      - name: Write deploy stamp (auto)
        run: |
          echo "deployed_at $(date -u +'%Y-%m-%dT%H:%M:%SZ') ${{ github.sha }}" > DEPLOY_STAMP.txt

      # ====== Docker ビルド & プッシュ（タグはコミットSHAのみ＝イミュータブル）======
      - name: Build and push image (no cache)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}
          no-cache: true

      # ====== 同一タッグの再プルで ECS を強制ロールアウト ======
      - name: Force new deployment (same tag pull)
        shell: bash
        run: |
          set -euo pipefail
          aws ecs update-service \
            --cluster "${CLUSTER_ARN}" \
            --service "${SERVICE_ARN}" \
            --force-new-deployment >/dev/null
          aws ecs wait services-stable \
            --cluster "${CLUSTER_ARN}" \
            --services "${SERVICE_ARN}"
