name: Rollback ECS service (one-click, previous revision)

on:
  workflow_dispatch: {}

jobs:
  rollback:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ap-northeast-1

      - name: Get current service/task info
        id: info
        run: |
          CLUSTER=voicebot-cluster
          SERVICE=svc-voicebot
          DESCRIBE=$(aws ecs describe-services --cluster $CLUSTER --services $SERVICE)
          CUR_TASKDEF=$(echo "$DESCRIBE" | jq -r '.services[0].taskDefinition')
          echo "cur_taskdef=$CUR_TASKDEF" >> $GITHUB_OUTPUT
          # 直近の過去2リビジョンを取得
          FAMILY=$(echo "$CUR_TASKDEF" | awk -F"/" '{print $2}' | awk -F":" '{print $1}')
          LIST=$(aws ecs list-task-definitions --family-prefix "$FAMILY" --sort DESC)
          PREV=$(echo "$LIST" | jq -r '.taskDefinitionArns[1]')
          echo "prev_taskdef=$PREV" >> $GITHUB_OUTPUT

      - name: Rollback service to previous task definition
        run: |
          CLUSTER=voicebot-cluster
          SERVICE=svc-voicebot
          PREV="${{ steps.info.outputs.prev_taskdef }}"
          echo "Rollback to $PREV"
          aws ecs update-service --cluster $CLUSTER --service $SERVICE --task-definition "$PREV"
          aws ecs wait services-stable --cluster $CLUSTER --services $SERVICE
